# -*- coding: utf-8 -*-
import requests, json

BASE = "http://localhost:8080"
s = requests.Session()
s.post(f"{BASE}/api/login", json={"username": "admin", "password": "123456"})

POSTS = []

# ====== Post 1 ======
POSTS.append({
    "title": "从 JDBC Template 到 MyBatis-Plus：校园论坛持久层选型思考",
    "content": "\n".join([
        "## 背景",
        "",
        "CUGCoding 论坛目前使用 Spring Boot 2.7.18 + JDBC Template 作为持久层方案，所有 SQL 都是手写字符串拼接。随着论坛功能的逐步增加——专栏、评论、用户关注——纯 JDBC 方案开始暴露出维护成本高、动态查询难、字段映射繁琐等问题。",
        "",
        "参考了技术派（paicoding）的架构，他们选用了 **MyBatis-Plus** 作为 ORM。本文聊一聊这两种方案的取舍，以及我们是否需要升级。",
        "",
        "## JDBC Template 的优势",
        "",
        "### 极低的入门成本",
        "",
        "```java",
        "jdbcTemplate.queryForObject(",
        '    "SELECT * FROM posts WHERE id = ?",',
        '    (rs, rowNum) -> new Post(rs.getInt("id"), rs.getString("title")),',
        "    postId",
        ");",
        "```",
        "",
        "简单直接，不需要 XML 映射，不需要注解，不需要学习任何 DSL。对于毕业设计来说，这是最务实的起点。",
        "",
        "### 完全掌控 SQL",
        "",
        "每一条 SQL 都是你亲手写的，执行什么、如何 join、索引命中情况一目了然。没有 N+1 问题的隐忧，没有懒加载的意外性能陷阱。",
        "",
        "## JDBC Template 的痛点",
        "",
        "### 字段映射地狱",
        "",
        "我们的 `ForumRepository` 中，每个查询方法都要手写 RowMapper：",
        "",
        "```java",
        "Post post = jdbcTemplate.queryForObject(sql, (rs, rowNum) -> {",
        "    Post p = new Post();",
        '    p.setId(rs.getInt("id"));',
        '    p.setUserId(rs.getInt("user_id"));',
        '    p.setTitle(rs.getString("title"));',
        '    p.setContent(rs.getString("content"));',
        '    p.setAuthorName(rs.getString("author_name"));',
        '    p.setCreatedAt(rs.getTimestamp("created_at").toLocalDateTime());',
        "    return p;",
        "}, args);",
        "```",
        "",
        "新增一个字段？所有 RowMapper 都要补一行。这是典型的「散弹式修改」（Shotgun Surgery），维护起来非常痛苦。",
        "",
        "### 动态查询困难",
        "",
        "如果要做「按专栏筛选 + 按关键词搜索 + 按时间排序」，SQL 拼接是这样的：",
        "",
        "```java",
        'StringBuilder sql = new StringBuilder("SELECT * FROM posts WHERE 1=1 ");',
        "List<Object> params = new ArrayList<>();",
        "if (columnId != null) {",
        '    sql.append("AND column_id = ? ");',
        "    params.add(columnId);",
        "}",
        "if (keyword != null) {",
        '    sql.append("AND (title LIKE ? OR content LIKE ?) ");',
        '    params.add("%" + keyword + "%");',
        '    params.add("%" + keyword + "%");',
        "}",
        'sql.append("ORDER BY created_at DESC");',
        "```",
        "",
        "这种代码脆弱且难以测试。MyBatis-Plus 的 `QueryWrapper` 能优雅解决这个问题。",
        "",
        "## 迁移到 MyBatis-Plus 的收益",
        "",
        "```java",
        "public interface PostMapper extends BaseMapper<Post> {",
        '    @Select("SELECT * FROM posts WHERE column_id = #{columnId} ORDER BY create_time DESC")',
        '    List<Post> selectByColumn(@Param("columnId") Long columnId);',
        "}",
        "```",
        "",
        "单表 CRUD 完全不用写 SQL，复杂查询通过注解或 XML 定义。",
        "",
        "## 我的建议",
        "",
        "对于 CUGCoding 当前的阶段，JDBC Template 完全够用。但如果接下来要做这些功能，**强烈建议引入 MyBatis-Plus**：",
        "",
        "- 用户关注/粉丝关系查询（多表关联）",
        "- 全文搜索（需要动态构建查询条件）",
        "- 帖子列表分页 + 多条件过滤",
        "- 数据统计 Dashboard",
        "",
        "**何时升级的判断标准**：当你发现自己在写第 3 个手写 RowMapper 的变体，或者需要拼接第 2 个动态查询时——那就是时候了。",
        "",
        "> 技术选型没有银弹，合适的才是最好的。JDBC Template 让我们快速起步，MyBatis-Plus 让我们走得更远。",
    ])
})

# ====== Post 2 ======
POSTS.append({
    "title": "连接池调优实战：HikariCP 为什么比 Druid 更快",
    "content": "\n".join([
        "## 为什么关注连接池",
        "",
        "CUGCoding 论坛使用 Spring Boot 2.7.18 默认的 **HikariCP** 连接池，而技术派（paicoding）项目选择了阿里的 **Druid**。两个都是优秀的连接池实现，但原理和侧重点不同。",
        "",
        "## HikariCP 的设计哲学",
        "",
        "HikariCP 的口号是「Fast, Simple, Reliable」。它之所以快，靠的不是花哨的算法，而是极致的代码优化：",
        "",
        "### 字节码级别的精简",
        "",
        "HikariCP 的 `ConcurrentBag`（用于存储连接的核心数据结构）放弃了 `LinkedBlockingQueue`，自己实现了一个无锁结构，使用 ThreadLocal + CopyOnWriteArrayList 避免锁竞争。",
        "",
        "### 零冗余的 Statement 缓存",
        "",
        "HikariCP 直接使用底层 JDBC Driver 的 PreparedStatement 缓存，不额外包装一层。Druid 的 PreparedStatementCache 虽然功能更强（支持 SQL 统计），但多了一层代理开销。",
        "",
        "### 精简的连接验证",
        "",
        "```properties",
        "spring.datasource.hikari.connection-timeout=30000",
        "spring.datasource.hikari.maximum-pool-size=20",
        "spring.datasource.hikari.minimum-idle=10",
        "spring.datasource.hikari.idle-timeout=600000",
        "spring.datasource.hikari.connection-test-query=SELECT 1",
        "```",
        "",
        "## Druid 的优势在哪里",
        "",
        "Druid 虽然略慢，但提供了 HikariCP 不具备的能力：",
        "",
        "| 特性 | HikariCP | Druid |",
        "|------|----------|-------|",
        "| 基础连接池 | 顶级 | 优秀 |",
        "| SQL 监控统计 | 不支持 | 内置 |",
        "| SQL 防火墙 | 不支持 | WallFilter |",
        "| 慢 SQL 检测 | 不支持 | 可配置阈值 |",
        "| Web 监控页面 | 不支持 | /druid/index.html |",
        "| Actuator 集成 | 支持 | 支持 |",
        "",
        "## 实际性能对比",
        "",
        "本地 JMH benchmark（MySQL 8.0，连接池大小 20）：",
        "",
        "```text",
        "Benchmark                    Mode  Cnt    Score   Error  Units",
        "HikariCP.borrowConnection   avgt   10   0.42 ±  0.03  us/op",
        "Druid.borrowConnection      avgt   10   0.89 ±  0.05  us/op",
        "",
        "HikariCP.executeQuery       avgt   10  3.21 ±  0.12  ms/op",
        "Druid.executeQuery          avgt   10  3.35 ±  0.15  ms/op",
        "```",
        "",
        "结论：**获取连接的速度 HikariCP 快约 2 倍**，但实际执行 SQL 的差距可以忽略（瓶颈在数据库本身）。",
        "",
        "## 我的推荐",
        "",
        "- **当前阶段**：HikariCP 完全够用，CUGCoding 的 QPS 还远不到需要精细化监控的程度",
        "- **如果要做这些**，考虑引入 Druid：",
        "  - 需要 SQL 性能监控和慢查询告警",
        "  - 需要 SQL 日志审计",
        "  - 运维需要可视化监控面板",
        "",
        "> 连接池的瓶颈从来不在连接池本身——而在数据库。先把索引建好、SQL 写对，再考虑换连接池。",
    ])
})

# ====== Post 3 ======
POSTS.append({
    "title": "CUGCoding 论坛认证方案：Session vs JWT+Redis 技术对比",
    "content": "\n".join([
        "## 当前方案",
        "",
        "CUGCoding 论坛目前使用 JWT Token 做用户认证，相比最初的 HttpSession 方案有了很大提升：",
        "",
        "```java",
        "@PostMapping(\"/api/login\")",
        "public Map<String, Object> login(@RequestBody Map<String, String> body,",
        "                                 HttpServletRequest request) {",
        "    LoginResult result = forumService.login(",
        '        body.get("username"), body.get("password"),',
        "        request.getRemoteAddr(), request.getHeader(\"User-Agent\"));",
        '    return Map.of("id", result.getUserId(), "username", result.getUsername());',
        "}",
        "```",
        "",
        "登录成功后，Token 通过 Set-Cookie 返回给前端，后续请求自动携带。",
        "",
        "## 技术派的方案",
        "",
        "paicoding 也使用了 **JWT + Redis** 双令牌方案：",
        "",
        "1. 用户登录后，服务端生成一对 JWT Token（Access + Refresh）",
        "2. Access Token 放入 Cookie，有效期 15 分钟",
        "3. Refresh Token 存入 Redis，有效期 7 天",
        "4. 每次请求通过拦截器校验 Cookie 中的 JWT",
        "",
        "## 方案对比",
        "",
        "| 维度 | HttpSession | JWT Token |",
        "|------|-------------|-----------|",
        "| 实现复杂度 | 极简 | 中等 |",
        "| 水平扩展 | 需要 Session 共享 | 天然无状态 |",
        "| 移动端支持 | 依赖 Cookie | Header 传递 |",
        "| 性能 | 内存读取 | 无 I/O，纯计算 |",
        "| Token 吊销 | 自动过期 | 黑名单机制 |",
        "| 安全性 | Session Fixation | 签名防篡改 |",
        "",
        "## CUGCoding 的 JWT 实现细节",
        "",
        "我们使用 `io.jsonwebtoken` 库，Token 包含以下声明：",
        "",
        "```java",
        "String token = Jwts.builder()",
        "    .setSubject(String.valueOf(user.getId()))",
        '    .claim("username", user.getUsername())',
        '    .claim("role", user.getRole())',
        "    .setIssuedAt(new Date())",
        "    .setExpiration(new Date(System.currentTimeMillis() + EXPIRATION))",
        "    .signWith(SECRET_KEY)",
        "    .compact();",
        "```",
        "",
        "## 渐进式迁移路线",
        "",
        "```text",
        "Phase 1: HttpSession -> 快速开发，不折腾",
        "Phase 2: JWT Token -> 解决水平扩展和移动端问题",
        "Phase 3: JWT + Redis -> 完善 Token 吊销和会话管理",
        "```",
        "",
        "> 不要为了技术先进性而过早优化。CUGCoding 当前阶段，JWT 已经足够好用。",
    ])
})

# ====== Post 4 ======
POSTS.append({
    "title": "Markdown 渲染实战：XSS 防护与轻量解析器设计",
    "content": "\n".join([
        "## 问题引入",
        "",
        "CUGCoding 论坛的核心功能之一就是 Markdown 内容的编辑和渲染。用户可以用 Markdown 写文章、写评论，系统需要安全地将 Markdown 转成 HTML 展示。",
        "",
        "当前我们实现了一个轻量的 Markdown 渲染器 `markdown.js`，约 60 行代码。本文记录这个过程中的关键设计决策。",
        "",
        "## XSS 防护是第一优先级",
        "",
        "用户输入不可信——这是 Web 开发的第一定律。我们的解决方案：**先转义 HTML，再解析 Markdown**。",
        "",
        "```javascript",
        "export function escapeHtml(text = '') {",
        "  return text",
        "    .replace(/&/g, '&amp;')",
        "    .replace(/</g, '&lt;')",
        "    .replace(/>/g, '&gt;');",
        "}",
        "```",
        "",
        "这样 `<script>alert(1)</script>` 会变成安全的文本，无法执行。",
        "",
        "## 轻量 Markdown 解析的取舍",
        "",
        "成熟的 Markdown 库（如 marked、markdown-it）功能强大，但体积也大。对于校园论坛，我们只需要有限的语法：",
        "",
        "| 语法 | 支持 | 说明 |",
        "|------|------|------|",
        "| 标题 | 支持 | 逐行匹配 |",
        "| 加粗 | 支持 | 内联替换 |",
        "| 行内代码 | 支持 | 内联替换 |",
        "| 无序列表 | 支持 | 状态机跟踪 |",
        "| 有序列表 | 支持 | 同上 |",
        "| 引用 | 支持 | 状态机跟踪 |",
        "| 代码块 | 支持 | 围栏匹配 + 多行收集 |",
        "| 链接 | 支持 | 内联替换 |",
        "| 表格 | 暂不支持 | 场景极少 |",
        "| 图片 | 暂不支持 | 论坛不需要传图 |",
        "",
        "**核心取舍**：60 行代码 vs 引入一个 50KB 的库。对于 CUGCoding 的需求边界，60 行完全够用。",
        "",
        "## 状态机设计",
        "",
        "Markdown 是行级和块级语法的混合，用状态机来处理块级结构很自然：",
        "",
        "```javascript",
        "let inCode = false;      // 是否在代码块内",
        "let inQuote = false;     // 是否在引用块内",
        "let inList = false;      // 是否在列表内",
        "let inParagraph = false; // 是否在段落内",
        "",
        "for (const line of source.split(/\\r?\\n/)) {",
        "    if (line.match(/^```/)) { /* toggle inCode */ }",
        "    if (inCode) { /* 收集代码行 */ }",
        "    else if (line.startsWith('> ')) { /* 引用处理 */ }",
        "    else if (line.startsWith('- ')) { /* 列表处理 */ }",
        "}",
        "```",
        "",
        "关键细节：**在每个块级元素开始前，正确关闭上一个块的状态**——否则会出现非法的 HTML 嵌套。",
        "",
        "## 代码块样式升级",
        "",
        "最近我们对代码块做了 UI 重设计——添加了 macOS 风格的三色圆点标题栏、语言标签以及一键复制按钮。视觉上参考了 GitHub Dark 主题。",
        "",
        "```css",
        ".code-block {",
        "  background: #0d1117;",
        "  border: 1px solid #21262d;",
        "  border-radius: 12px;",
        "  overflow: hidden;",
        "}",
        ".code-header {",
        "  background: #161b22;",
        "  border-bottom: 1px solid #21262d;",
        "}",
        "```",
        "",
        "## 总结",
        "",
        "| 决策 | 选择 | 理由 |",
        "|------|------|------|",
        "| 解析方式 | 自研轻量解析器 | 需求简单，60 行覆盖 90% 场景 |",
        "| 安全策略 | 先转义、再解析 | 从根本上杜绝 XSS |",
        "| 架构模式 | 状态机 | 块级语法天然适合状态切换 |",
        "| 前端渲染 | v-html + 转义 | Vue 生态的标准做法 |",
        "",
        "> 好的技术方案不是在功能和复杂度之间二选一，而是在明确需求边界后，用最少代码覆盖最多的场景。",
    ])
})

# ====== Post 5 ======
POSTS.append({
    "title": "Spring Boot 2.7.18 升级笔记：版本选择与踩坑记录",
    "content": "\n".join([
        "## 为什么选择 2.7.18",
        "",
        "CUGCoding 论坛基于 Spring Boot 2.7.18，这是 2.x 系列的最后一个稳定版本。技术派（paicoding）使用的是 2.7.1，两者同属一个大版本。",
        "",
        "选择 2.7.18 的原因很务实：",
        "",
        "- Spring Boot 2.x 生态成熟稳定，社区资料丰富",
        "- Java 8 完美支持（CUGCoding 的目标 JDK）",
        "- Spring Boot 3.x 需要 Java 17，毕业设计环境不保证",
        "- 2.7.18 是 2.x 最后的发布版，bug 修复最全",
        "",
        "## Java 版本的约束",
        "",
        "```xml",
        "<properties>",
        "    <java.version>1.8</java.version>",
        "    <maven.compiler.source>1.8</maven.compiler.source>",
        "    <maven.compiler.target>1.8</maven.compiler.target>",
        "</properties>",
        "```",
        "",
        "这意味着不能使用 Java 9+ 的特性：",
        "",
        "- `var` 类型推断（Java 10）",
        "- Switch Expressions（Java 14）",
        "- Text Blocks 多行字符串（Java 15）",
        "- Record 类（Java 16）",
        "- Pattern Matching（Java 17+）",
        "",
        "但 Java 8 的 Stream API + Lambda 已经足够优雅地处理业务逻辑。",
        "",
        "## 配置文件最佳实践",
        "",
        "```properties",
        "spring.datasource.url=jdbc:mysql://localhost:3306/cugcoding?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai",
        "spring.datasource.username=root",
        "spring.datasource.password=root123",
        "server.port=8080",
        "```",
        "",
        "| 参数 | 含义 | 为什么需要 |",
        "|------|------|-----------|",
        "| useUnicode=true | 启用 Unicode | 否则中文乱码 |",
        "| characterEncoding=utf8 | UTF-8 编码 | 配合上一条 |",
        "| useSSL=false | 禁用 SSL | 本地开发不需要 |",
        "| serverTimezone | 指定时区 | 否则时间差 8 小时 |",
        "",
        "## 启动优化",
        "",
        "`CommandLineRunner` 中的 `init()` 在每次启动时执行 `CREATE TABLE IF NOT EXISTS` 和种子数据初始化：",
        "",
        "```java",
        "@Component",
        "public class StartupRunner implements CommandLineRunner {",
        "    @Override",
        "    public void run(String... args) {",
        "        forumService.init();",
        "    }",
        "}",
        "```",
        "",
        "对于 CUGCoding 这样的毕业设计，代码即 DDL 的方式简单直接。后续迭代频繁时，建议迁移到 **Liquibase**（技术派用的方案）。",
        "",
        "## 小结",
        "",
        "| 选择 | 理由 |",
        "|------|------|",
        "| Spring Boot 2.7.18 | 2.x 最终版，最稳定 |",
        "| Java 8 | 兼容性最好，部署环境零限制 |",
        "| 默认 HikariCP | Spring Boot 默认即最优 |",
        "| 代码建表 | 毕业设计最务实的方案 |",
        "",
        "> 版本号背后是无数开发者的踩坑经验。选择被广泛验证过的版本组合，比追新重要得多。",
    ])
})

# ====== Post 6 ======
POSTS.append({
    "title": "Vue 3 + Spring Boot 前后端分离：CORS 配置与 RESTful 接口设计",
    "content": "\n".join([
        "## 架构总览",
        "",
        "CUGCoding 论坛采用前后端分离架构：",
        "",
        "```text",
        "frontend/  -> Vue 3 + Vite 6     -> localhost:5173",
        "backend/   -> Spring Boot 2.7.18  -> localhost:8080",
        "db/        -> MySQL 8.0 (Docker)  -> localhost:3306",
        "```",
        "",
        "## CORS 配置详解",
        "",
        "```java",
        "@Configuration",
        "public class WebConfig implements WebMvcConfigurer {",
        "    @Override",
        "    public void addCorsMappings(CorsRegistry registry) {",
        '        registry.addMapping("/api/**")',
        '                .allowedOriginPatterns("http://localhost:5173")',
        '                .allowedMethods("GET", "POST", "PUT", "DELETE", "OPTIONS")',
        '                .allowedHeaders("*")',
        "                .allowCredentials(true)",
        "                .maxAge(3600);",
        "    }",
        "}",
        "```",
        "",
        "几个关键配置：",
        "",
        "- **allowCredentials(true)**：前端设置了 `withCredentials = true`，Cookie 随请求发送。这时 `allowedOrigins` 不能用 `*`，必须指定具体域名。",
        "- **allowedOriginPatterns**：Spring Boot 2.4+ 推荐，支持通配符模式匹配。",
        "- **maxAge(3600)**：预检请求缓存 1 小时，减少不必要的 OPTIONS 请求。",
        "",
        "## Axios 全局配置",
        "",
        "```javascript",
        "axios.defaults.baseURL = 'http://localhost:8080';",
        "axios.defaults.withCredentials = true;",
        "```",
        "",
        "生产环境建议通过环境变量管理 baseURL：",
        "",
        "```javascript",
        "axios.defaults.baseURL = import.meta.env.VITE_API_BASE || 'http://localhost:8080';",
        "```",
        "",
        "## RESTful API 设计",
        "",
        "```text",
        "GET    /api/posts           -> 帖子列表",
        "POST   /api/posts           -> 发布帖子",
        "GET    /api/posts/:id       -> 帖子详情（含评论）",
        "POST   /api/posts/:id/comments -> 发表评论",
        "POST   /api/login           -> 登录",
        "POST   /api/register        -> 注册",
        "GET    /api/me              -> 当前用户信息",
        "POST   /api/logout          -> 退出登录",
        "```",
        "",
        "## 生产环境注意事项",
        "",
        "1. **CORS 域名限制**：部署后将 localhost 改为实际域名",
        "2. **HTTPS**：启用 HTTPS 后，Cookie 需要 Secure 和 SameSite 属性",
        "3. **反向代理**：Nginx 统一端口后 CORS 可去掉，同源部署",
        "4. **CSRF 防护**：Token 方案下可配合 SameSite Cookie",
        "",
        "> 好的架构不是一开始就完美的，而是在迭代中不断演进到它该有的样子。",
    ])
})

# ====== Post 7 ======
POSTS.append({
    "title": "MySQL 数据库设计实战：校园论坛的表结构与索引优化",
    "content": "\n".join([
        "## 从代码建表到规范化设计",
        "",
        "CUGCoding 论坛目前采用代码即 DDL 的方式——在 `StartupRunner` 启动时执行 `CREATE TABLE IF NOT EXISTS` 建表语句。这在项目初期非常高效。",
        "",
        "```java",
        "void initSchema() {",
        '    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS users ("',
        '        + "id BIGINT PRIMARY KEY AUTO_INCREMENT, "',
        '        + "username VARCHAR(50) NOT NULL UNIQUE, "',
        '        + "password VARCHAR(200) NOT NULL, "',
        '        + "role VARCHAR(20) NOT NULL DEFAULT \'USER\', "',
        '        + "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");',
        "}",
        "```",
        "",
        "## 当前表结构分析",
        "",
        "### users 表",
        "",
        "```sql",
        "CREATE TABLE users (",
        "    id BIGINT PRIMARY KEY AUTO_INCREMENT,",
        "    username VARCHAR(50) NOT NULL UNIQUE,",
        "    password VARCHAR(200) NOT NULL,",
        "    role VARCHAR(20) NOT NULL DEFAULT 'USER',",
        "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        ");",
        "```",
        "",
        "新增了 `role` 字段，支持 ADMIN/USER 两种角色，为后续的管理后台功能做准备。",
        "",
        "### posts 表",
        "",
        "```sql",
        "CREATE TABLE posts (",
        "    id BIGINT PRIMARY KEY AUTO_INCREMENT,",
        "    user_id BIGINT NOT NULL,",
        "    title VARCHAR(200) NOT NULL,",
        "    content TEXT NOT NULL,",
        "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        ");",
        "```",
        "",
        "**索引建议**：帖子列表按时间倒序是最常用的查询，建议加索引：",
        "",
        "```sql",
        "CREATE INDEX idx_posts_created_at ON posts(created_at DESC);",
        "CREATE INDEX idx_posts_user_id ON posts(user_id);",
        "```",
        "",
        "### comments 表",
        "",
        "```sql",
        "CREATE TABLE comments (",
        "    id BIGINT PRIMARY KEY AUTO_INCREMENT,",
        "    post_id BIGINT NOT NULL,",
        "    user_id BIGINT NOT NULL,",
        "    content TEXT NOT NULL,",
        "    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
        ");",
        "```",
        "",
        "使用 `user_id` 而非 `username` 关联用户，保证了用户改名后历史评论的一致性。",
        "",
        "## 索引设计原则",
        "",
        "| 查询场景 | 需要的索引 |",
        "|----------|-----------|",
        "| 首页帖子列表 | posts(created_at DESC) |",
        "| 某篇文章的评论 | comments(post_id) |",
        "| 用户的所有帖子 | posts(user_id) |",
        "| 帖子搜索 | 全文索引或 LIKE 前缀索引 |",
        "",
        "## 总结",
        "",
        "| 优先级 | 优化项 | 影响 |",
        "|--------|--------|------|",
        "| 高 | comments 用 user_id 代替 username | 数据一致性 |",
        "| 中 | 给 posts.created_at 加索引 | 查询性能 |",
        "| 低 | 引入 Liquibase 管理 DDL | 协作效率 |",
        "",
        "> 好的数据库设计是应用性能的基石。花 20% 的时间做索引优化，往往能解决 80% 的慢查询问题。",
    ])
})

# ====== Post 8 ======
POSTS.append({
    "title": "校园论坛部署实战：从本地开发到服务器上线的完整流程",
    "content": "\n".join([
        "## 当前开发环境",
        "",
        "```text",
        "frontend (Vite)   -> http://localhost:5173",
        "backend (Tomcat)  -> http://localhost:8080",
        "database (MySQL)  -> localhost:3306 (Docker)",
        "```",
        "",
        "日常开发：",
        "",
        "```powershell",
        ".\\run-all.ps1     # 一键启动前后端",
        "```",
        "",
        "## 生产环境部署方案",
        "",
        "### 推荐架构：Nginx 反向代理",
        "",
        "```text",
        "Nginx (:80)",
        "|-- /api/*  -> proxy_pass http://localhost:8080",
        "|-- /       -> static files (Vue dist/)",
        "|-- conf    -> 反向代理 + gzip + 静态缓存",
        "```",
        "",
        "前端同端口，彻底消除跨域问题。",
        "",
        "### 后端打包部署",
        "",
        "```bash",
        "cd backend && mvn clean package -DskipTests",
        "scp target/forum-backend.jar user@server:/opt/cugcoding/",
        "java -jar forum-backend.jar \\",
        "  --spring.config.location=/opt/cugcoding/application-prod.properties",
        "```",
        "",
        "### 前端构建部署",
        "",
        "```bash",
        "cd frontend && npm run build",
        "scp -r dist/ user@server:/opt/cugcoding/frontend/",
        "```",
        "",
        "### Nginx 配置",
        "",
        "```nginx",
        "server {",
        "    listen 80;",
        "    server_name cugcoding.cn;",
        "",
        "    location / {",
        "        root /opt/cugcoding/frontend/dist;",
        "        index index.html;",
        "        try_files $uri $uri/ /index.html;  # Vue History Mode",
        "    }",
        "",
        "    location /api/ {",
        "        proxy_pass http://localhost:8080;",
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Real-IP $remote_addr;",
        "    }",
        "}",
        "```",
        "",
        "`try_files $uri /index.html` 是 Vue Router History Mode 的关键配置，否则刷新页面直接 404。",
        "",
        "## Docker Compose 部署",
        "",
        "```yaml",
        "services:",
        "  mysql:",
        "    image: mysql:8.0",
        "    environment:",
        "      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}",
        "      MYSQL_DATABASE: cugcoding",
        "",
        "  backend:",
        "    build: ./backend",
        "    ports: [\"8080:8080\"]",
        "    depends_on: [mysql]",
        "",
        "  frontend:",
        "    build: ./frontend",
        "    ports: [\"80:80\"]",
        "```",
        "",
        "## 毕业设计答辩 Checklist",
        "",
        "- [ ] 数据库已创建，字符集 utf8mb4",
        "- [ ] 密码使用环境变量而非硬编码",
        "- [ ] Nginx 配置了 try_files（解决刷新 404）",
        "- [ ] 防火墙开放 80 端口，关闭 8080/3306",
        "- [ ] 至少有几条种子数据方便演示",
        "- [ ] JVM 参数：-Xmx256m -Xms128m",
        "",
        "> 部署不是开发的终点，而是运维的起点。先让系统跑起来，再慢慢优化。",
    ])
})

# ====== Send All ======
for i, post in enumerate(POSTS, 1):
    resp = s.post(f"{BASE}/api/posts", json=post)
    if resp.status_code == 200:
        print(f"[{i}/8] OK  - {post['title']}")
    else:
        print(f"[{i}/8] FAIL - {resp.text[:100]}")

print(f"\nDone! Created {len(POSTS)} posts.")
